In [9]:
import torch

### Tensor

In [4]:
a = torch.ones(2,2, requires_grad=True)
print(a)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [6]:
b = a+2
print(b)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [7]:
print(b.grad_fn)

In [8]:
c = b*b*3
out = c.mean()
print(c,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [10]:
from __future__ import print_function
import torch

In [11]:
a = torch.empty(6,3)
print(a)

tensor([[9.2755e-39, 1.0653e-38, 1.0469e-38],
        [2.9389e-39, 8.9082e-39, 9.2755e-39],
        [2.9388e-39, 1.0469e-38, 1.0837e-38],
        [9.9184e-39, 1.0010e-38, 2.9389e-39],
        [8.9082e-39, 9.2755e-39, 2.9389e-39],
        [1.1112e-38, 1.0653e-38, 1.1020e-38]])


In [12]:
a = torch.rand(4,3)
print(a)

tensor([[0.7138, 0.2961, 0.3662],
        [0.2027, 0.8693, 0.8205],
        [0.8300, 0.6037, 0.7620],
        [0.4990, 0.8016, 0.6536]])


In [14]:
a = torch.zeros(4,3, dtype= torch.long)
print(a)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [16]:
a = torch.tensor([8.7,5])
print(a)
type(a)

tensor([8.7000, 5.0000])


torch.Tensor

In [17]:
a = a.new_ones(6,5, dtype=torch.double)
print(a)

a = torch.randn_like(a, dtype=torch.float)
print(a)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)
tensor([[ 3.3438e-01,  5.8200e-01, -3.1531e+00,  3.1633e-01,  7.1546e-01],
        [-2.3468e-01,  1.0025e+00,  1.3347e+00,  8.3717e-01,  4.8084e-01],
        [-4.3578e-01,  9.5103e-01, -1.0260e+00, -2.3138e-01, -1.0096e+00],
        [-3.5188e-01, -6.2308e-02,  6.1322e-01,  1.6235e-03,  6.6882e-01],
        [ 4.3498e-01,  5.1204e-04, -1.9267e-01, -1.2808e+00,  2.1282e-01],
        [-1.0861e+00,  6.9253e-01,  7.6114e-01, -5.0238e-01,  1.6814e-01]])


In [18]:
print(a.size())

torch.Size([6, 5])


### operations

In [19]:
b = torch.rand(6,5)
print(a+b)

tensor([[ 0.5879,  1.4647, -2.7322,  0.5129,  1.4696],
        [ 0.6483,  1.8267,  1.8839,  1.4250,  1.3133],
        [-0.2600,  1.4131, -0.9048,  0.0234, -0.1545],
        [ 0.2319,  0.2242,  0.9381,  0.3362,  0.7348],
        [ 1.3719,  0.8333,  0.1070, -0.8632,  1.2125],
        [-0.7316,  0.7192,  1.7209,  0.2004,  0.8254]])


In [20]:
print(torch.add(a,b))

tensor([[ 0.5879,  1.4647, -2.7322,  0.5129,  1.4696],
        [ 0.6483,  1.8267,  1.8839,  1.4250,  1.3133],
        [-0.2600,  1.4131, -0.9048,  0.0234, -0.1545],
        [ 0.2319,  0.2242,  0.9381,  0.3362,  0.7348],
        [ 1.3719,  0.8333,  0.1070, -0.8632,  1.2125],
        [-0.7316,  0.7192,  1.7209,  0.2004,  0.8254]])


In [24]:
result = torch.empty(6,5)
torch.add(a,b, out = result)
print(result)

tensor([[ 0.5879,  1.4647, -2.7322,  0.5129,  1.4696],
        [ 0.6483,  1.8267,  1.8839,  1.4250,  1.3133],
        [-0.2600,  1.4131, -0.9048,  0.0234, -0.1545],
        [ 0.2319,  0.2242,  0.9381,  0.3362,  0.7348],
        [ 1.3719,  0.8333,  0.1070, -0.8632,  1.2125],
        [-0.7316,  0.7192,  1.7209,  0.2004,  0.8254]])


In [25]:
# adds a to b
b.add_(a)
print(b)

tensor([[ 0.5879,  1.4647, -2.7322,  0.5129,  1.4696],
        [ 0.6483,  1.8267,  1.8839,  1.4250,  1.3133],
        [-0.2600,  1.4131, -0.9048,  0.0234, -0.1545],
        [ 0.2319,  0.2242,  0.9381,  0.3362,  0.7348],
        [ 1.3719,  0.8333,  0.1070, -0.8632,  1.2125],
        [-0.7316,  0.7192,  1.7209,  0.2004,  0.8254]])


In [26]:
b.add(a)
print(a)
print(b)

tensor([[ 3.3438e-01,  5.8200e-01, -3.1531e+00,  3.1633e-01,  7.1546e-01],
        [-2.3468e-01,  1.0025e+00,  1.3347e+00,  8.3717e-01,  4.8084e-01],
        [-4.3578e-01,  9.5103e-01, -1.0260e+00, -2.3138e-01, -1.0096e+00],
        [-3.5188e-01, -6.2308e-02,  6.1322e-01,  1.6235e-03,  6.6882e-01],
        [ 4.3498e-01,  5.1204e-04, -1.9267e-01, -1.2808e+00,  2.1282e-01],
        [-1.0861e+00,  6.9253e-01,  7.6114e-01, -5.0238e-01,  1.6814e-01]])
tensor([[ 0.5879,  1.4647, -2.7322,  0.5129,  1.4696],
        [ 0.6483,  1.8267,  1.8839,  1.4250,  1.3133],
        [-0.2600,  1.4131, -0.9048,  0.0234, -0.1545],
        [ 0.2319,  0.2242,  0.9381,  0.3362,  0.7348],
        [ 1.3719,  0.8333,  0.1070, -0.8632,  1.2125],
        [-0.7316,  0.7192,  1.7209,  0.2004,  0.8254]])


In [27]:
print(a[:,2])

tensor([-3.1531,  1.3347, -1.0260,  0.6132, -0.1927,  0.7611])


### tensor.view
We can resize or reshape tensor, use tensor.view

In [28]:
a = torch.randn(3,3)
b = a.view(9)
c =a.view(-1,9)
print(a.size(), b.size(), c.size())

torch.Size([3, 3]) torch.Size([9]) torch.Size([1, 9])


### .item()

In [29]:
a = torch.randn(1)
print(a)
print(a.item())

tensor([0.1494])
0.14943161606788635


### NumPy Bridge

#####  Converting a Torch tensor to NumPy

In [30]:
x = torch.ones(4)
print(x)

tensor([1., 1., 1., 1.])


In [31]:
y = x.numpy()
print(y)

[1. 1. 1. 1.]


##### Converting NumPy array to Torch tensor

In [33]:
import numpy as np
f = np.ones(4)
g = torch.from_numpy(f)

np.add(f,1, out=f)
print(f)
print(g)

[2. 2. 2. 2.]
tensor([2., 2., 2., 2.], dtype=torch.float64)
