In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.14.0'

In [4]:
# create TensorFlow object called tensor
hello_constant = tf.constant('Hello World')
hello_constant


<tf.Tensor 'Const_1:0' shape=() dtype=string>

In [5]:
with tf.Session() as sess:
    # Run the tf.constant operation in the session
    output = sess.run(hello_constant)
    print(output)

b'Hello World'


### Tensors

In [6]:
A = tf.constant(1234)
# B is a 1-dimensional int32 tensor
b = tf.constant([123,456,789])

C = tf.constant([[123,456,789],[222,333,444]])
C

<tf.Tensor 'Const_4:0' shape=(2, 3) dtype=int32>

### Session

In [9]:
with tf.Session() as sess:
    output = sess.run(C)
    print(output)

[[123 456 789]
 [222 333 444]]


### TensorFlow Input

In [10]:
A = tf.constant(34335)
x = tf.placeholder(tf.string)

### tf.placeholder()

In [11]:
with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 'hello world'})
    print(output)

hello world


In [13]:
x = tf.placeholder(tf.string)
y = tf.placeholder(tf.int32)
z = tf.placeholder(tf.float32)

with tf.Session() as sess:
    output_x = sess.run(x, feed_dict={x: 'hello world',y:123,z:45.5})
    output_y = sess.run(y, feed_dict={y: 'hello world',y:123,z:45.5})
    print(output_x)
    print(output_y)

hello world
123


### TensorFlow Math

In [16]:
x = tf.add(5,2)
x

<tf.Tensor 'Add_1:0' shape=() dtype=int32>

In [18]:
with tf.Session() as sess:
    output_s = sess.run(x)
    print(output_s)

7


In [19]:
y = tf.subtract(6,7)

### Conversion Types

In [21]:
tf.subtract(tf.cast(tf.constant(2.0), tf.int32), tf.constant(1))

<tf.Tensor 'Sub_1:0' shape=() dtype=int32>

In [23]:
x = tf.constant(10)
y = tf.constant(2)
z = tf.subtract(tf.divide(x,y),1)

with tf.Session() as sess:
    output_d = sess.run(z)
    print(output_d)

4.0


# tf.Variable()

In [24]:
x = tf.Variable(5)


In [25]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    sess.run(x)

# tf.truncated_normal()

In [27]:
n_features = 120
n_labels = 5
weights = tf.Variable(tf.truncated_normal((n_features, n_labels)))

In [29]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    o = tf.truncated_normal((n_features, n_labels))
    print(o)

Tensor("truncated_normal_2:0", shape=(120, 5), dtype=float32)


In [30]:
import numpy as np
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# tf.zeros()

In [32]:
n_labels = 5
bias = tf.Variable(tf.zeros(n_labels))

In [34]:
x = tf.nn.softmax([2.0,1.0,0.2])
with tf.Session() as sess:
    o = sess.run(x)
    print(o)

[0.65223986 0.23994564 0.10781453]


In [17]:
def run_2():
    output = None
    logit_data= [2.0,1.0,0.1]
    logits = tf.placeholder(tf.float32)
    
    softmax = tf.nn.softmax(logit_data)
    with tf.Session() as sess:
        output = sess.run(softmax, feed_dict= {logits:logit_data})
    return(output)
    
print(run_2())

[0.6590012  0.24243298 0.09856589]


### Reduce Sum

In [18]:
import tensorflow as tf


In [19]:
x = tf.reduce_sum([1,2,3,4,5])


### Natural Log

In [22]:
l = tf.log(100.0)

In [25]:
with tf.Session() as sess:
    output_x = sess.run(x)
    output_l = sess.run(l)
    print(output_x)
    print(output_l)

15
4.6051702


### Print the cross entropy using softmax_data and one_hot_encod_label

In [27]:
import tensorflow as tf

softmax_data = [0.7,0.2,0.1]
one_hot_data = [1.0,0,0]

softmax = tf.placeholder(tf.float32)
one_hot = tf.placeholder(tf.float32)

# Print cross entropy from session
cross_entropy = -tf.reduce_sum(tf.multiply(one_hot, tf.log(softmax)))

with tf.Session() as sess:
    output = sess.run(cross_entropy, feed_dict= {one_hot : one_hot_data, softmax: softmax_data})
    print(output)

0.35667497
